### ISSUE TITLE
[Captcher] A few different feature ideas

### ISSUE THREAD

**Issue by EpicLPer** [Predeactor/Predeactor-Cogs#19]
# Options

- [ ] Related to an issue: (Mention the issue)
- [ ] Breaking change(s).
- [X] Related to a cog. (Captcher)

# Contents

A few feature requests I'd find useful :) 

- **Wrong Message Kick Amount:** So far the bot will immediately kick you if you enter the Captcha wrong. Let the admin decide how many times a user is allowed to enter it incorrectly before yeeting the user.
- **Refresh Captcha**: Let the user refresh the captcha via an Emoji reaction or "refresh" in the chat if the captcha is unreadable
- **Timeout Adjust**: Adjust the amount of time the user has to solve the captcha
- **Edit Message**: Allow to edit the message the bot sends, or optionally allow users to completely turn this off and use "welcomeset" from Trusty-cogs to send a more customizable message which will also get auto-deleted once the user enters the captcha in/correctly

\---

**Optional:**
- **Normal Chatting:** Let the user write messages in the verify channel without the captcha plugin thinking he's trying to solve the captcha. As example, if the message doesn't start with a number don't interpret this as a solve attempt, maybe the user has some other issues he wants to discuss first.

Thanks!

**Comment by Predeactor** [comment]
Hey, thanks for your suggestion, here is my reply:

Wrong Message Kick Amount
- Would you mind explaining again? I did not understood.

**Refresh Captcha**
- This is a good idea, sometime, some captcha are hard to guess and this will help.

**Timeout Adjust**
- I think about it, but this is possible.

Edit Message
- I already think about it already, and I'm unsure about it, starting by how I could handle certain things.

Normal Chatting
- No. The used channel *should* be used for passing captcha only, not for talking.

**Comment by Predeactor** [comment]
After reading again, I think I may be able to give an answer.

> So far the bot will immediately kick you if you enter the Captcha wrong. Let the admin decide how many times a user is allowed to enter it incorrectly before yeeting the user.

Actually, the user is getting kicked if the bot is missing permissions to manage verification channel, since it try to mute the user in case he want to say anything else that shouldn't be in the channel.
However if muting has been successful, bot will wait 5 seconds, I guess this is possible to change this amount time, but I'm quite not understanding if it be useful.

**Comment by EpicLPer** [comment]
> After reading again, I think I may be able to give an answer.
> 
> > So far the bot will immediately kick you if you enter the Captcha wrong. Let the admin decide how many times a user is allowed to enter it incorrectly before yeeting the user.
> 
> Actually, the user is getting kicked if the bot is missing permissions to manage verification channel, since it try to mute the user in case he want to say anything else that shouldn't be in the channel.
> However if muting has been successful, bot will wait 5 seconds, I guess this is possible to change this amount time, but I'm quite not understanding if it be useful.

Could you mention this in the logs channel? Something along the lines "Failed to mute User after failed captcha attempt, User was kicked from server due to bot missing permissions".

**Comment by Predeactor** [comment]
It is already a thing, bot will add "(Immediate Kick)" at modlog message and logs message.
However I will indicate in logs channel that bot is missing permissions.

**Comment by Predeactor** [comment]
Here's a final message that will close the discussion and put the points on the development of Captcher. (Now Captcha)

> Wrong Message Kick Amount (Adjust the limit of failed attempts or disable it completely)

Will be available.

> Refresh Captcha (The option to refresh/regenerate a new captcha)

Will be available in next update.

> Timeout Adjust (Adjust the limit of failed attempts or disable it completely)

Will be available in the future. Talking about it, it is impossible for me to disable it completely.

> Edit Message (Edit the captcha message)

Will be available in next update.

> Automatic verification
The current captcha bot I am using uses AI/machine learning to do most of the heavy work but sometimes it automatically verifies spam accounts and there isn't much you can do to change that. Maybe, if possible, add a setting that allows you to set the criteria for automatic verification (account age, has profile picture, ksoft bans etc)

Will be not available, I prefer that all users pass the captcha in order to join the server.

If you still want to add suggestions, feel free to add a comment.
