### ISSUE TITLE
Check if Channel Permissions

### ISSUE THREAD

**Issue by aless2003** [Predeactor/Predeactor-Cogs#29]
# Options

- [ ] Related to an issue: (Mention the issue)
- [ ] Breaking change(s).
- [x] Related to a cog. (Tell what cog)

# Contents
[Captcha]
There should be a check for the `setcaptcha channel` Method. It should check the temp role if one was set and else the normal user with no role.

**Comment by Predeactor** [comment]
After thinking of it, I think this issue shouldn't be "fixed".
I know that permissions can be a *bad* thing when they're not done well in a server, and I get that, but I don't want to restrain the Captcha's configuration just because of a misleading permissions configuration. In top of that, there's multiple way that these permissions could be set to due to a specific case, and there can also be other cogs running in the server.

I'll be closing this issue, but I'll maybe think of another approach to handle this. Thought, this will take his time.
